FROM postgres:15

ENV POSTGRES_USER=me
ENV POSTGRES_PASSWORD=1111111
ENV POSTGRES_DB=my
ENV PGDATA=/var/lib/postgresql/data/pgdata

VOLUME ["/var/lib/postgresql/data", "/docker-entrypoint-initdb.d"]

EXPOSE 5432

CMD ["postgres"]

