# Use an official Python runtime as the base image
FROM python:3.11

# Set the working directory in the container


# Copy the application files from GitHub
RUN git clone https://github.com/ushdream/fastapi_service.git /app

WORKDIR /app
#RUN pip install pydantic-settings
#RUN pip install pydantic[email]

# 

RUN pip install --no-cache-dir --upgrade -r /app/src/requirements.txt

#RUN pip install pydantic-settings

EXPOSE 8200
#CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8200"]
#RUN apt-get update && apt-get install -y python3.11

#CMD alembic upgrade head
CMD alembic upgrade head && python3 src/main.py
