version: '3'

# rev 1.

networks:
  ya_net:
    driver: bridge

services:
  pg:
    build:
      context: .
      dockerfile: Dockerfile-pg
    networks:
      - ya_net
    ports:
      - "5932:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 10

  fapi:
    build:
      context: .
      dockerfile: Dockerfile-fapi
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - ya_net
    ports:
      - "8000:8000"
    environment:
      - DATABASE_DSN=postgresql+asyncpg://me:1111111@pg:5432/my