"""01_initial-db

Revision ID: 2c5b3f38ebcd
Revises: 2c3a3dbc3e6e
Create Date: 2023-09-30 10:26:18.096557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c5b3f38ebcd'
down_revision = '2c3a3dbc3e6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_logger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('by_user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_url_logger_by_user'), 'url_logger', ['by_user'], unique=True)
    op.create_index(op.f('ix_url_logger_created_at'), 'url_logger', ['created_at'], unique=False)
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_original', sa.String(length=256), nullable=False),
    sa.Column('url_short', sa.String(length=256), nullable=False),
    sa.Column('url_owner', sa.String(length=256), nullable=False),
    sa.Column('privacy_read', sa.Boolean(), nullable=False),
    sa.Column('privacy_change', sa.Boolean(), nullable=False),
    sa.Column('privacy_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_original'),
    sa.UniqueConstraint('url_short')
    )
    op.create_index(op.f('ix_urls_created_at'), 'urls', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user'), 'users', ['user'], unique=True)
    op.drop_index('ix_entity_created_at', table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entity_pkey'),
    sa.UniqueConstraint('title', name='entity_title_key')
    )
    op.create_index('ix_entity_created_at', 'entity', ['created_at'], unique=False)
    op.drop_index(op.f('ix_users_user'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_urls_created_at'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_url_logger_created_at'), table_name='url_logger')
    op.drop_index(op.f('ix_url_logger_by_user'), table_name='url_logger')
    op.drop_table('url_logger')
    # ### end Alembic commands ###
