"""01_initial-db

Revision ID: 5fd5d56bf574
Revises: fb330ce9671c
Create Date: 2023-10-02 03:25:29.156885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd5d56bf574'
down_revision = 'fb330ce9671c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_user', table_name='users')
    op.drop_table('users')
    op.drop_column('urls', 'privacy_change')
    op.drop_column('urls', 'url_owner')
    op.drop_column('urls', 'privacy_delete')
    op.drop_column('urls', 'privacy_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('privacy_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('urls', sa.Column('privacy_delete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('urls', sa.Column('url_owner', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('urls', sa.Column('privacy_change', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_user', 'users', ['user'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
