"""01_initial-db

Revision ID: a3f3ff457cf9
Revises: bec8c840618e
Create Date: 2023-10-01 20:49:46.888010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f3ff457cf9'
down_revision = 'bec8c840618e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_logger', sa.Column('url_short', sa.String(length=256), nullable=False))
    op.drop_index('ix_url_logger_by_user', table_name='url_logger')
    op.drop_constraint('url_logger_url_key', 'url_logger', type_='unique')
    op.drop_column('url_logger', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_logger', sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint('url_logger_url_key', 'url_logger', ['url'])
    op.create_index('ix_url_logger_by_user', 'url_logger', ['by_user'], unique=False)
    op.drop_column('url_logger', 'url_short')
    # ### end Alembic commands ###
