"""01_initial-db

Revision ID: fac9624fb89d
Revises: 
Create Date: 2023-10-17 09:48:35.423191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac9624fb89d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_logger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_short', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('by_user', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_logger_created_at'), 'url_logger', ['created_at'], unique=False)
    op.create_table('urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_original', sa.String(length=256), nullable=False),
    sa.Column('url_short', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_original'),
    sa.UniqueConstraint('url_short')
    )
    op.create_index(op.f('ix_urls_created_at'), 'urls', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=256), nullable=False),
    sa.Column('secret_hashed', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_urls_created_at'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_url_logger_created_at'), table_name='url_logger')
    op.drop_table('url_logger')
    # ### end Alembic commands ###
